### ISSUE TITLE
Skew in mobile AR

### ISSUE THREAD

**Issue by ben-mantis** [ben-mantis/docomo-app#1]
In mobile (I am using  Xiaomi Pocophobe, android) when the asset is shown, we can see clearly the asset is stretched.
I have tried changing the scale parameters in file src\components\arViewer.js there is initScene function which originated from src\components\utility\meshHelper.js (also tried to change there... with no luck)

Although I can see the changes in src\components\guiViewer.js, in mobile it doesn't change.

<img src="https://user-images.githubusercontent.com/75925788/107344250-ee5de100-6aca-11eb-940e-3540237a7d8f.jpeg" width="300">

**Comment by robco5** [comment]
Put you phone horizontally a tell me if it is different...

Might be related to camera FOV or viewport setup

**Comment by ben-mantis** [comment]
It still skewed, although in another axis I think.

<img src="https://user-images.githubusercontent.com/75925788/107355709-8910ec80-6ad8-11eb-9b8c-a25bddb811e7.jpeg" width="300">

**Comment by robco5** [comment]
So it really looks as viewport or camera setup issue. Some values are used to initialize it, but not reflecting image resolution/size/acpect on screen...
